# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Release PHAR"

on:
  release:
    types:
      - published

jobs:
  release-phar:
    name: "Release PHAR"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "7.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - uses: DeterminateSystems/nix-installer-action@v9

      - name: "Build PHAR"
        run: |
          "nix run .#build-phar-script"

      - name: "Upload PHAR"
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
